# Generated by Django 5.0.6 on 2024-07-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_lecturer_courselecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLecturer',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
